apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  annotations:
    jenkins.io/openshift-mode: "true"
  creationTimestamp: "2020-01-17T15:31:09Z"
  generation: 9
  name: example
  namespace: vpogu-sandbox
  resourceVersion: "807055"
  selfLink: /apis/jenkins.io/v1alpha2/namespaces/vpogu-sandbox/jenkins/example
  uid: 62a5260c-393e-11ea-80cd-06449304231e
spec:
  backup:
    action: {}
    containerName: ""
    interval: 0
    makeBackupBeforePodDeletion: false
  configurationAsCode:
    configurations: jenkins-operator-user-configuration
  groovyScripts:
    configurations: null
    secret:
      name: ""
  master:
    basePlugins:
      - name: kubernetes
        version: 1.18.3
      - name: workflow-job
        version: "2.34"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: 3.12.0
      - name: job-dsl
        version: "1.76"
      - name: configuration-as-code
        version: "1.29"
      - name: configuration-as-code-support
        version: "1.19"
      - name: kubernetes-credentials-provider
        version: 0.12.1
      - name: bitbucket-plugin
        version: 1.1.11
    containers:
      - command:
          - /usr/bin/go-init
          - "-main"
          - /usr/libexec/s2i/run
        env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "false"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: DISABLE_ADMINISTRATIVE_MONITORS
            value: "false"
          - name: KUBERNETES_MASTER
            value: "https://kubernetes.default:443"
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: JENKINS_SERVICE_NAME
            value: jenkins-operator-http-example
          - name: JNLP_SERVICE_NAME
            value: jenkins-operator-slave-example
          - name: JENKINS_UC_INSECURE
            value: "false"
          - name: JENKINS_HOME
            value: /var/lib/jenkins
          - name: JAVA_OPTS
            value: >-
              -XX:+UnlockExperimentalVMOptions -XX:+UnlockExperimentalVMOptions
              -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
              -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
        image: "quay.io/openshift/origin-jenkins:latest"
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 360
          successThreshold: 1
          timeoutSeconds: 240
        name: jenkins-master
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        resources:
          limits:
            cpu: 600m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 3Gi
    disableCSRFProtection: false
    securityContext:
      fsGroup: 1000520000
      runAsUser: 1000520023
      seLinuxOptions:
        level: "s0:c23,c7"
  restore:
    action: {}
    containerName: ""
  service:
    port: 8080
    type: ClusterIP
  slaveService:
    port: 50000
    type: ClusterIP
status:
  operatorVersion: v0.2.2
  provisionStartTime: "2020-01-17T15:37:52Z"
  userAndPasswordHash: pAuxEisk490WUKVNdfhoJPxiS0sdBdhNJX51xnGFAtA=
