apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    beta.kubernetes.io/arch: amd64
  containers:
    - name: docker
      # image: docker:19.03.12
      image: vikaspogu/docker-buildx-qemu:latest
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /root/.docker
          subPath: config.json
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: docker-daemon
      image: docker:19.03.12-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: kubectl
      image: vikaspogu/kubectl:1.18.5
      command:
        - sleep
      args:
        - 99d
  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
